[package]
name = "terms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.164", features=["derive"]}
toml = "0.7.4"
serde-xml-rs = "0.5"
regex = "1.9.6"
