[[tags]]
id = "mev"
description = "Maximal extractable value"

[[tags]]
id = "zk"
description = "Zero Knowledge Proofs"

[[tags]]
id = "defi"
description = "Decentralized Finance"

[[tags]]
id = "protocol"
description = "Ethereum Protocol"

[[tags]]
id = "layer2"
description = "Layer 2"
